model: NGCF
epochs: 20
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
dataset: ml-100k
embedding_size: 64
hidden_size_list:
- 64
- 64
message_dropout: 0.1
node_dropout: 0.0
reg_weight: 1.0e-05
